[project]
name = "concurrency-and-parallelism"
version = "0.2.0"
description = "Concurrency and parallelism pass-it-on"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
]
